name: CI Pipeline
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
      - name: Build
        run: npm run build
      - name: Versioning
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          npm version patch -m "Bump version to %s"
          git push origin --tags
      - name: Send email on failure
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: Pipeline Failure
          to: fe.dsm.vot.001@gmail.com
          from: Matheus Prusch
          body: Pipeline failed. Check GitHub Actions.
